baseURL = "/"
languageCode = "en-us"
title = "imazine.de"
theme="imazine"
LanguageCode="de-1996"


[menu]
  [[menu.main]]
    identifier = "imprint-privacy"
    name = "Impressum und Datenschutzerkl√§rung"
    url = "/imprint-privacy"
